"""Creates only fictional, synthetic demonstration input data."""
from pathlib import Path
import fitz

PAGES = [
("AUTOSAR HLD Demonstration", "SYNTHETIC DEMONSTRATION DATA — NOT AN OEM DOCUMENT\n\nDocument: Aurora Vehicle Platform High-Level Design\nRevision: 0.3 | Status: Demonstration\n\nPurpose: This fictional document describes a small body-and-comfort control architecture for demonstrating retrieval, citations, and grounded AI answers."),
("1. Architecture Overview", "The Aurora platform separates application components from communication and hardware abstraction services. Vehicle Application Manager coordinates driving-mode and comfort requests. Sensor Manager normalizes sensor readings. Actuator Manager sends validated commands to physical actuators. Diagnostic Manager records health events. Communication Manager routes network messages through the CAN Interface."),
("2. Vehicle Application Manager", "Vehicle Application Manager (VAM) is the orchestration component. It receives door-state, cabin-temperature, and diagnostic-status inputs, applies simple feature rules, and requests actions from Door Control Component and Climate Control Component. VAM depends on Communication Manager for network-originated requests and Diagnostic Manager for degraded-mode status. Provided port: VehicleFeatureControl. Required ports: DoorStatus, ClimateStatus, DiagnosticStatus."),
("3. Door Control Component", "Door Control Component controls fictional door-lock and window functions. Its provided port DoorService accepts LockRequest and WindowPositionRequest. It requires the DoorPosition signal from Sensor Manager and LockActuation service from Actuator Manager. A lock request is rejected when Diagnostic Manager reports a door actuator fault. DoorStateStatus is published to Vehicle Application Manager through Communication Manager."),
("4. Climate Control Component", "Climate Control Component maintains a requested cabin temperature. It consumes CabinTemperature from Sensor Manager and ClimateSetpoint from Vehicle Application Manager. It requests BlowerCommand and AirMixCommand from Actuator Manager. The component publishes ClimateStatus. When a sensor plausibility fault is active, it holds the last safe blower level and reports the condition to Diagnostic Manager."),
("5. Communication Architecture", "Communication Manager coordinates communication between application components and the CAN Interface. It maps application messages to fictional CAN frames and distributes received frames to subscribed components. CAN Interface owns controller access and validates frame timing. Example signals: DoorLockRequest (CAN ID 0x221), CabinSetpoint (CAN ID 0x315), DoorStateStatus (CAN ID 0x222). Communication Manager depends on CAN Interface; application components depend on Communication Manager rather than directly accessing CAN."),
("6. Sensor and Actuator Services", "Sensor Manager acquires DoorPosition, CabinTemperature, and OutsideTemperature signals, checks range plausibility, and publishes normalized values. Actuator Manager accepts authorized service requests and controls the DoorLockActuator, WindowMotor, BlowerMotor, and AirMixFlap. Sensor Manager reports implausible values to Diagnostic Manager. Actuator Manager confirms execution status to requesting components."),
("7. Diagnostics", "Diagnostic Manager collects diagnostic events from all components, stores fictional diagnostic trouble codes, and publishes DiagnosticStatus. Example DTC: DTC-DOOR-001 means door lock actuator response timeout. Example DTC: DTC-CLIM-014 means cabin-temperature sensor plausibility failure. During an active fault, Diagnostic Manager informs Vehicle Application Manager and the relevant component so that each can use its documented safe behavior."),
("8. Functional Flows", "Door lock flow: a CAN DoorLockRequest reaches CAN Interface, then Communication Manager, then Door Control Component. Door Control checks DoorPosition and DiagnosticStatus, requests LockActuation from Actuator Manager, and publishes DoorStateStatus. Climate flow: CabinTemperature moves from Sensor Manager to Climate Control Component; VAM provides ClimateSetpoint; Climate Control requests blower and air-mix actions from Actuator Manager."),
("9. Interface and Dependency Table", "Component | Provides | Requires\nVehicle Application Manager | VehicleFeatureControl | DoorStatus, ClimateStatus, DiagnosticStatus\nDoor Control Component | DoorService | DoorPosition, LockActuation, DiagnosticStatus\nClimate Control Component | ClimateStatus | CabinTemperature, ClimateSetpoint, BlowerCommand\nCommunication Manager | MessageRouting | CAN Interface\nSensor Manager | NormalizedSignals | Sensors\nActuator Manager | ActuationService | Authorized requests\n\nRevision note: 0.3 adds documented climate sensor safe behavior."),
("10. Constraints and Summary", "This demonstration architecture is fictional and is not an OEM implementation. It is intended only for a student RAG prototype. Safety, cybersecurity, timing analysis, calibration, and detailed AUTOSAR configuration are outside scope. Human engineering review is required before any real automotive use.")]

def main():
    out = Path(__file__).resolve().parents[1] / "Input_Data" / "sample_hld.pdf"
    doc = fitz.open()
    for heading, body in PAGES:
        page = doc.new_page()
        page.insert_textbox(fitz.Rect(54, 54, 540, 760), heading + "\n\n" + body, fontsize=12, fontname="helv", lineheight=1.45)
        page.insert_text((54, 800), "Synthetic demonstration document | Aurora Platform", fontsize=8, color=(0.4,0.4,0.4))
    doc.set_metadata({"title":"Aurora Vehicle Platform HLD (Synthetic Demonstration)", "author":"Student Capstone Demo"})
    doc.save(out)
    print(out)
if __name__ == "__main__": main()
